// <auto-generated />
using System;
using AE5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AE5.Migrations
{
    [DbContext(typeof(PlaceMyBetContext))]
    [Migration("20201214173145_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AE5.Models.Apuesta", b =>
                {
                    b.Property<int>("ApuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Cuota")
                        .HasColumnType("double");

                    b.Property<double>("DineroApuesta")
                        .HasColumnType("double");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MercadoId")
                        .HasColumnType("int");

                    b.Property<double>("OverUnder")
                        .HasColumnType("double");

                    b.Property<string>("TipoApuesta")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ApuestaId");

                    b.HasIndex("MercadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apuesta");

                    b.HasData(
                        new
                        {
                            ApuestaId = 12,
                            Cuota = 1.8999999999999999,
                            DineroApuesta = 20.0,
                            EventoId = 1,
                            Fecha = new DateTime(2020, 12, 14, 18, 31, 45, 312, DateTimeKind.Local).AddTicks(1493),
                            MercadoId = 1000,
                            OverUnder = 1.5,
                            TipoApuesta = "over",
                            UsuarioId = "usuario1@gmail.com"
                        });
                });

            modelBuilder.Entity("AE5.Models.Cuenta", b =>
                {
                    b.Property<string>("CuentaId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Saldo")
                        .HasColumnType("double");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("CuentaId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Cuenta");

                    b.HasData(
                        new
                        {
                            CuentaId = "12345678",
                            Nombre = "BBVA",
                            Saldo = 360.25,
                            UsuarioId = "usuario1@gmail.com"
                        });
                });

            modelBuilder.Entity("AE5.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EquipoLocal")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EquipoVisitante")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventoId");

                    b.ToTable("Evento");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            EquipoLocal = "Valencia",
                            EquipoVisitante = "Barcelona",
                            Fecha = new DateTime(2020, 12, 14, 18, 31, 45, 308, DateTimeKind.Local).AddTicks(1606)
                        });
                });

            modelBuilder.Entity("AE5.Models.Mercado", b =>
                {
                    b.Property<int>("MercadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CuotaOver")
                        .HasColumnType("double");

                    b.Property<double>("CuotaUnder")
                        .HasColumnType("double");

                    b.Property<double>("DineroOver")
                        .HasColumnType("double");

                    b.Property<double>("DineroUnder")
                        .HasColumnType("double");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<double>("OverUnder")
                        .HasColumnType("double");

                    b.HasKey("MercadoId");

                    b.HasIndex("EventoId");

                    b.ToTable("Mercado");

                    b.HasData(
                        new
                        {
                            MercadoId = 1000,
                            CuotaOver = 1.8999999999999999,
                            CuotaUnder = 1.8999999999999999,
                            DineroOver = 50.0,
                            DineroUnder = 50.0,
                            EventoId = 1,
                            OverUnder = 1.5
                        });
                });

            modelBuilder.Entity("AE5.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = "usuario1@gmail.com",
                            Apellido = "Conches",
                            Edad = 21,
                            Nombre = "Noelia"
                        });
                });

            modelBuilder.Entity("AE5.Models.Apuesta", b =>
                {
                    b.HasOne("AE5.Models.Mercado", "mercado")
                        .WithMany()
                        .HasForeignKey("MercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AE5.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("AE5.Models.Cuenta", b =>
                {
                    b.HasOne("AE5.Models.Usuario", "usuario")
                        .WithOne("cuenta")
                        .HasForeignKey("AE5.Models.Cuenta", "UsuarioId");
                });

            modelBuilder.Entity("AE5.Models.Mercado", b =>
                {
                    b.HasOne("AE5.Models.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
